# Generated by Django 4.0.4 on 2022-04-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
    ]
