# Generated by Django 4.0.4 on 2022-05-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.PositiveSmallIntegerField(default=2, null=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
