# Generated by Django 4.0.4 on 2022-05-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_users_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
