# Generated by Django 4.0.4 on 2022-05-18 01:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandOwner', models.CharField(default=False, max_length=255)),
                ('name', models.TextField()),
                ('fdc_id', models.IntegerField()),
                ('category', models.TextField()),
                ('publication_date', models.DateField()),
                ('marketCountry', models.CharField(max_length=255)),
                ('nutrients', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('food', models.CharField(max_length=255)),
                ('fdc_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrients', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'nutrients',
            },
        ),
        migrations.CreateModel(
            name='SRLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('fdc_id', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('nutrients', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nutrients', models.TextField()),
                ('dataType', models.CharField(default='SR Legacy', max_length=15)),
                ('brandOwner', models.CharField(default=False, max_length=255)),
                ('favorite', models.ManyToManyField(related_name='favorite_food', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'foods',
            },
        ),
    ]
