# Generated by Django 4.0.4 on 2022-05-18 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branded',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_branded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='srlegacy',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite_sr_legacy', to=settings.AUTH_USER_MODEL),
        ),
    ]
