# Generated by Django 4.0.4 on 2022-04-28 21:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0002_alter_food_food_alter_food_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='nutrients',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='publication',
            field=models.DateTimeField(),
        ),
    ]
