# Generated by Django 4.0.4 on 2022-05-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_foodhistory_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodhistory',
            name='nutrients',
        ),
    ]
