# Generated by Django 4.0.4 on 2022-04-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
