# Generated by Django 4.0.4 on 2022-04-28 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0003_food_nutrients_alter_food_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='publication',
        ),
    ]
