# Generated by Django 4.0.4 on 2022-05-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_foodhistory_nutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='brandOwner',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
