# Generated by Django 4.0.4 on 2022-05-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_foodhistory_delete_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='dataType',
            field=models.CharField(default='SR Legacy', max_length=15),
        ),
    ]
