# Generated by Django 4.0.4 on 2022-04-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0004_remove_food_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrients', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'nutrients',
            },
        ),
    ]
