# Generated by Django 4.0.4 on 2022-04-29 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0005_nutrients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food',
            new_name='name',
        ),
    ]
