# Generated by Django 4.0.4 on 2022-04-30 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0002_delete_users'),
        ('foods', '0006_rename_food_food_name'),
    ]

    operations = [
    ]
