# Generated by Django 4.0.4 on 2022-04-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0007_merge_0002_delete_users_0006_rename_food_food_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_box', models.CharField(max_length=255)),
                ('radio_brand',
                 models.CharField(choices=[('SR Legacy', 'SR Legacy'), ('Branded Foods', 'Branded Foods')],
                                  max_length=15)),
            ],
        ),
    ]
