# Generated by Django 4.0.4 on 2022-05-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0008_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('nutrients', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
