# Generated by Django 4.0.4 on 2022-05-01 07:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0009_addfoodhistory_delete_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddFoodHistory',
        ),
    ]
