# Generated by Django 4.0.4 on 2022-05-01 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0011_foodhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodHistory',
        ),
    ]
