# Generated by Django 4.0.4 on 2022-05-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0012_delete_foodhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('food', models.CharField(max_length=255)),
                ('nutrients', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
