# Generated by Django 4.0.4 on 2022-05-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0015_alter_foodhistory_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodhistory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
