# Generated by Django 4.0.4 on 2022-05-03 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0003_search'),
        ('foods', '0016_alter_foodhistory_date'),
    ]

    operations = [
    ]
