# Generated by Django 4.0.4 on 2022-05-03 00:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('foods', '0017_merge_0003_search_0016_alter_foodhistory_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
