from django.shortcuts import render, HttpResponse
from django.views.generic import View
from foods.models import FoodHistory

import ast


# Create your views here.
class ProfileView(View):
    template_name = 'profile.html'
    model = FoodHistory

    def get(self, request):
        return render(request, 'profile.html', {'daily_goal': self.daily_goal()})

    def update_history(self):
        qs = self.model.objects.filter(username=self.request.user.username).values('food', 'nutrients')
        return qs

    def daily_goal(self):
        history = self.update_history()
        food = [item['food'] for item in history]
        nutrients = [item['nutrients'] for item in history]
        nutrients = ast.literal_eval(nutrients[0])

        for val in nutrients:

        nutrient_dict = {
            "Alanine": "",
            "Alcohol, ethyl": "",
            "Arginine": "",
            "Ash": "",
            "Aspartic acid": "",
            "Beta-sitosterol": "",
            "Betaine": "",
            "Caffeine": "",
            "Calcium, Ca": "",
            "Campesterol": "",
            "Carbohydrate, by difference": "",
            "Carotene, alpha": "",
            "Carotene, beta": "",
            "Cholesterol": "",
            "Choline, total": "",
            "Copper, Cu": "",
            "Cryptoxanthin, beta": "",
            "Cystine": "",
            "Energy": "",
            "Fatty acids, total monounsaturated": "",
            "Fatty acids, total polyunsaturated": "",
            "Fatty acids, total saturated": "",
            "Fatty acids, total trans": "",
            "Fatty acids, total trans-monoenoic": "",
            "Fatty acids, total trans-polyenoic": "",
            "Fiber, total dietary": "",
            "Fluoride, F": "",
            "Folate, DFE": "",
            "Folate, food": "",
            "Folate, total": "",
            "Folic acid": "",
            "Fructose": "",
            "Galactose": "",
            "Glucose (dextrose)": "",
            "Glutamic acid": "",
            "Glycine": "",
            "Histidine": "",
            "Hydroxyproline": "",
            "Iron, Fe": "",
            "Isoleucine": "",
            "Lactose": "",
            "Leucine": "",
            "Lutein + zeaxanthin": "",
            "Lycopene": "",
            "Lysine": "",
            "MUFA 14:1": "",
            "MUFA 15:1": "",
            "MUFA 16:1": "",
            "MUFA 16:1 c": "",
            "MUFA 17:1": "",
            "MUFA 18:1": "",
            "MUFA 18:1 c": "",
            "MUFA 18:1-11 t (18:1t n-7)": "",
            "MUFA 20:1": "",
            "MUFA 22:1": "",
            "MUFA 22:1 c": "",
            "MUFA 24:1 c": "",
            "Magnesium, Mg": "",
            "Maltose": "",
            "Manganese, Mn": "",
            "Methionine": "",
            "Niacin": "",
            "PUFA 18:2": "",
            "PUFA 18:2 CLAs": "",
            "PUFA 18:2 i": "",
            "PUFA 18:2 n-6 c,c": "",
            "PUFA 18:3": "",
            "PUFA 18:3 n-3 c,c,c (ALA)": "",
            "PUFA 18:3 n-6 c,c,c": "",
            "PUFA 18:3i": "",
            "PUFA 18:4": "",
            "PUFA 20:2 n-6 c,c": "",
            "PUFA 20:3": "",
            "PUFA 20:3 n-3": "",
            "PUFA 20:3 n-6": "",
            "PUFA 20:4": "",
            "PUFA 21:5": "",
            "PUFA 22:4": "",
            "PUFA 22:5 n-3 (DPA)": "",
            "PUFA 22:6 n-3 (DHA)": "",
            "PUFA 2:4 n-6": "",
            "PUFA 2:5 n-3 (EPA)": "",
            "Pantothenic acid": "",
            "Phenylalanine": "",
            "Phosphorus, P": "",
            "Phytosterols": "",
            "Potassium, K": "",
            "Proline": "",
            "Protein": "",
            "Retinol": "",
            "Riboflavin": "",
            "SFA 10:0": "",
            "SFA 12:0": "",
            "SFA 13:0": "",
            "SFA 14:0": "",
            "SFA 15:0": "",
            "SFA 16:0": "",
            "SFA 17:0": "",
            "SFA 18:0": "",
            "SFA 20:0": "",
            "SFA 22:0": "",
            "SFA 24:0": "",
            "SFA 4:0": "",
            "SFA 6:0": "",
            "SFA 8:0": "",
            "Selenium, Se": "",
            "Serine": "",
            "Sodium, Na": "",
            "Starch": "",
            "Stigmasterol": "",
            "Sucrose": "",
            "Sugars, total including NLEA": "",
            "TFA 16:1 t": "",
            "TFA 18:1 t": "",
            "TFA 18:2 t not further defined": "",
            "TFA 18:2 t,t": "",
            "TFA 22:1 t": "",
            "Theobromine": "",
            "Thiamin": "",
            "Threonine": "",
            "Tocopherol, beta": "",
            "Tocopherol, delta": "",
            "Tocopherol, gamma": "",
            "Tocotrienol, alpha": "",
            "Tocotrienol, beta": "",
            "Tocotrienol, delta": "",
            "Tocotrienol, gamma": "",
            "Total lipid (fat)": "",
            "Tryptophan": "",
            "Tyrosine": "",
            "Valine": "",
            "Vitamin A, IU": "",
            "Vitamin A, RAE": "",
            "Vitamin B-12": "",
            "Vitamin B-12, added": "",
            "Vitamin B-6": "",
            "Vitamin C, total ascorbic acid": "",
            "Vitamin D (D2 + D3)": "",
            "Vitamin D (D2 + D3), International Units": "",
            "Vitamin D2 (ergocalciferol)": "",
            "Vitamin D3 (cholecalciferol)": "",
            "Vitamin E (alpha-tocopherol)": "",
            "Vitamin E, added": "",
            "Vitamin K (Dihydrophylloquinone)": "",
            "Vitamin K (Menaquinone-4)": "",
            "Vitamin K (phylloquinone)": "",
            "Water": "",
            "Zinc, Zn": ""
        }

        return temp
