name: Django CI
env:
  POSTGRES_HOST: localhost
  DB_HOST: localhost
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ${{ secrets.DB_KEY }}
on:
  push:
    branches: [ "testing-pages" ]
  pull_request:
    branches: [ "testing-pages" ]


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_KEY: ${{ secrets.DB_KEY }} 
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: food_base
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_KEY }}
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        sudo apt-get -y install postgresql-12
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run Tests
      run: |
        python ./food_track/manage.py test
    - name: Connect to PostgreSQL
      # Runs a script that creates a PostgreSQL table, populates
      # the table with data, and then retrieves the data. todo
      run: |
        sudo service postgresql start
        # python ./config/client.py
      # env:
      #   # The hostname used to communicate with the PostgreSQL service container
      #   POSTGRES_HOST: postgres
      #   # The default PostgreSQL port
      #   POSTGRES_PORT: 5432
    - name: Migrations
      run: |
        python ./food_track/manage.py makemigrations
        python ./food_track/manage.py migrate
    - name: Startserver
      run: |
        python ./food_track/manage.py runserver
